### ISSUE TITLE
Error Running .\build.ps1

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [Jaykul/WASP#2]
First off- thanks for making this it looks useful. Unfortunately, I'm having trouble actually building it.

PS Version Table:
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Problem:** 
I received an error when trying to build WASP.
Error: https://pastebin.com/UTt44bhi

**Steps to reproduce:**
1. Clone source code from Github. 
2. Install Module Builder using "Install-Module ModuleBuilder" in a Windows PowerShell administrator window.
3. In the PowerShell administrator window use "cd" to get to the path containing the build.ps1 file.
4. Try to run ".\build.ps1" (without the quotation marks) in a PowerShell window with administrator permissions.
5. Watch the error occur. 

I opened the file and it mentions Get-Type at this line:
`$patterns = Get-Type -Assembly UIAComWrapper -Base System.Windows.Automation.BasePattern`

**Comment by ocmca** [comment]
I had a similar issue, and forked and shared my fix for it. Hopefully this helps? Let me know if you found your own solution.

https://github.com/ocmca/WASP

**Comment by PiggiesGoSqueal** [comment]
> I had a similar issue, and forked and shared my fix for it. Hopefully this helps? Let me know if you found your own solution.
> 
> https://github.com/ocmca/WASP

I looked into alternatives and will probably end up using Python with PyWin32, PyWinAuto, and/or PyAutoGUI. However, I appreciate the reply and if I end up going back to WASP I'll definitely try that fix out, thanks!
